# Generated by Django 3.1.7 on 2021-02-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('task', models.CharField(max_length=500)),
            ],
        ),
    ]
